// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package snowflake

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCurrentAccount(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetCurrentAccountResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetCurrentAccountResult
	err := ctx.Invoke("snowflake:index/getCurrentAccount:getCurrentAccount", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getCurrentAccount.
type GetCurrentAccountResult struct {
	// The Snowflake Account ID; as returned by CURRENT_ACCOUNT().
	Account string `pulumi:"account"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The Snowflake Region; as returned by CURRENT_REGION()
	Region string `pulumi:"region"`
	// The Snowflake URL.
	Url string `pulumi:"url"`
}
