// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package snowflake

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetResourceMonitors(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetResourceMonitorsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetResourceMonitorsResult
	err := ctx.Invoke("snowflake:index/getResourceMonitors:getResourceMonitors", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getResourceMonitors.
type GetResourceMonitorsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The resource monitors in the database
	ResourceMonitors []GetResourceMonitorsResourceMonitor `pulumi:"resourceMonitors"`
}
