// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package snowflake

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetWarehouses(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetWarehousesResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetWarehousesResult
	err := ctx.Invoke("snowflake:index/getWarehouses:getWarehouses", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getWarehouses.
type GetWarehousesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The warehouses in the database
	Warehouses []GetWarehousesWarehouse `pulumi:"warehouses"`
}
